version: "3"

services:
  web:
    build: .
    depends_on:
      - mongo
      - redis
    volumes:
      - "./var/www/series"
    ports: 
      - "4006:4002"
  mongo:
    image: "mongo:4.4"
    ports:
      - "17017:27017"
    command: mongod
  redis:
    image: "redis"
    command: redis-server