version: "3"

services:
  mongo:
    image: "mongo:4.4"
    ports:
      - "17017:27017"
    command: mongod
  redis:
    image: "redis"
    ports:
      - "5379:6379"
    command: 
      - redis-server
  web:
    build: .
    depends_on:
      - mongo
      - redis
    volumes:
      - ".:/var/www/entertainMe"
    ports: 
      - "4007:4000"